services:
  springboot:
    image: thsdnjsdlr12/sbapiserver:latest
    build: .

    ports:
      - "33080:33080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: rhdoddldml!1423
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "rhdoddldml!1423"]